// node scripts/verify_viewport_details_zoom.mjs <playwright-package-dir> <agent-browser-cdp-url>
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const { chromium } = createRequire(import.meta.url)(process.argv[2]);
const browser = await chromium.connectOverCDP(process.argv[3]);
const page = browser.contexts()[0].pages().find(p => p.url().startsWith('http://localhost:3000'));
const output = path.resolve(import.meta.dirname, '../outputs/runtime/viewport_details_zoom');
await mkdir(output, { recursive: true });
const report = { checks: [], errors: [], passed: false };
page.on('pageerror', error => report.errors.push(error.message));
const check = name => { report.checks.push(name); console.log('PASS', name); };
const shot = name => page.screenshot({ path: path.join(output, `${name}.png`) });
const height = page.locator('#scene-height-detail');
const scale = page.locator('#scene-scale-detail');
const zoom = page.getByRole('dialog', { name: 'Original image', exact: true });
const zoomStage = page.locator('.source-image-stage');
const ready = () => page.getByRole('button', { name: 'Enlarge original image', exact: true }).waitFor();
try {
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.reload();
  await page.getByRole('button', { name: 'Load Urban demonstration', exact: true }).click();
  await ready();
  assert.equal(await height.isVisible(), false); assert.equal(await scale.isVisible(), false);
  await shot('windowed-collapsed');
  check('Both bottom panels default collapsed in windowed mode');
  await page.getByRole('button', { name: 'Height info', exact: true }).click();
  assert.equal(await height.isVisible(), true); assert.equal(await scale.isVisible(), false);
  const heightText = await height.innerText();
  await page.getByRole('button', { name: 'Map scale', exact: true }).click();
  assert.equal(await height.isVisible(), false); assert.equal(await scale.isVisible(), true);
  await page.waitForFunction(() => Boolean(document.querySelector('.scene-scale-ruler')?.dataset.length));
  await shot('windowed-scale');
  await page.getByRole('button', { name: 'Close map scale', exact: true }).click();
  assert.equal(await scale.isVisible(), false);
  await page.getByRole('button', { name: 'Height info', exact: true }).click();
  assert.equal(await height.innerText(), heightText);
  await page.getByRole('button', { name: 'Height info', exact: true }).click();
  assert.equal(await height.isVisible(), false);
  check('Only requested panel opens; close/toggle work and live values are unchanged');
  const meshBefore = await page.locator('.terrain-canvas').getAttribute('data-terrain-mesh');
  await page.getByRole('button', { name: 'Enlarge original image', exact: true }).click();
  await zoom.waitFor();
  await page.waitForFunction(() => document.querySelector('.source-image-dialog img')?.naturalWidth > 0);
  assert.equal(new URL(await zoom.locator('img').getAttribute('src'), page.url()).pathname, '/demo/copenhagen_rgb.jpg');
  assert.equal(await zoomStage.getAttribute('data-zoom'), '1');
  await page.getByRole('button', { name: 'Zoom in original image', exact: true }).click();
  await page.getByRole('button', { name: 'Zoom in original image', exact: true }).click();
  assert.ok(Number(await zoomStage.getAttribute('data-zoom')) > 1);
  const box = await zoomStage.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 70, box.y + box.height / 2 + 40, { steps: 5 }); await page.mouse.up();
  assert.ok(Number(await zoomStage.getAttribute('data-pan-y')) > 0);
  const zoomBefore = Number(await zoomStage.getAttribute('data-zoom'));
  await page.mouse.wheel(0, -100); await page.waitForTimeout(150);
  assert.ok(Number(await zoomStage.getAttribute('data-zoom')) > zoomBefore);
  await shot('zoom-pan');
  await page.getByRole('button', { name: 'Fit image', exact: true }).click();
  assert.equal(await zoomStage.getAttribute('data-zoom'), '1');
  assert.equal(await zoomStage.getAttribute('data-pan-y'), '0');
  await page.keyboard.press('+'); await page.waitForTimeout(80);
  assert.ok(Number(await zoomStage.getAttribute('data-zoom')) > 1);
  await page.keyboard.press('0');
  assert.equal(await zoomStage.getAttribute('data-zoom'), '1');
  await shot('image-fit');
  await page.keyboard.press('Escape');
  assert.equal(await zoom.count(), 0);
  assert.equal(await page.locator('.terrain-canvas').getAttribute('data-terrain-mesh'), meshBefore);
  check('Image click opens modal; buttons/wheel/keyboard zoom, drag pan, Fit and Esc work without changing mesh');
  await page.getByRole('button', { name: 'FULLSCREEN', exact: true }).click();
  await page.waitForTimeout(250);
  assert.equal(await height.isVisible(), true); assert.equal(await scale.isVisible(), true);
  assert.equal(await page.locator('.scene-detail-controls').count(), 0);
  await shot('fullscreen-expanded');
  await page.getByRole('button', { name: 'Enlarge original image', exact: true }).click();
  await zoom.waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await zoom.count(), 0);
  assert.notEqual(await page.locator('.viewport').getAttribute('data-fullscreen-kind'), 'off');
  await page.getByRole('button', { name: 'EXIT FULLSCREEN', exact: true }).click();
  assert.equal(await height.isVisible(), false); assert.equal(await scale.isVisible(), false);
  check('Fullscreen keeps both panels expanded; image Esc does not exit fullscreen; returning collapses panels');
  await page.getByRole('button', { name: 'Height info', exact: true }).click();
  await page.getByRole('button', { name: 'Load Hilly demonstration', exact: true }).click();
  await ready();
  assert.equal(await height.isVisible(), false);
  await page.getByRole('button', { name: 'Enlarge original image', exact: true }).click();
  await zoom.waitFor();
  assert.equal(new URL(await zoom.locator('img').getAttribute('src'), page.url()).pathname, '/demo/landscapes/hilly/texture.jpg');
  await page.getByRole('button', { name: 'Close original image', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Map scale', exact: true }).click();
  const scaleBox = await scale.boundingBox();
  assert.ok(scaleBox.x >= 0 && scaleBox.x + scaleBox.width <= 391);
  await shot('mobile-scale');
  await page.getByRole('button', { name: 'Close map scale', exact: true }).click();
  await page.getByRole('button', { name: 'Enlarge original image', exact: true }).click();
  const dialogBox = await zoom.boundingBox();
  assert.ok(dialogBox.x >= 0 && dialogBox.x + dialogBox.width <= 391 && dialogBox.y + dialogBox.height <= 844);
  await shot('mobile-image');
  await page.getByRole('button', { name: 'Close original image', exact: true }).click();
  check('New scene resets panel selection and enlarged source; controls and modal fit narrow screens');
  assert.deepEqual(report.errors, []);
  report.passed = true;
} catch (error) {
  report.failure = error.stack; process.exitCode = 1; console.error(error);
  await shot('failure').catch(() => {});
} finally {
  await writeFile(path.join(output, 'verification.json'), JSON.stringify(report, null, 2));
  await browser.close();
}
